webtalk_init -webtalk_dir C:/Users/abuba/Desktop/CMOD Test/CMOD Test.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar  2 19:07:38 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "96314e87-e037-4144-810c-8aef3ae793bc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9cb9a1aab57143b08e39b4d380466e83" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2600 Six-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "549 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "31 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "221" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "15" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.56_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "128252_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2772170871 -regid "" -xml C:/Users/abuba/Desktop/CMOD Test/CMOD Test.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/abuba/Desktop/CMOD Test/CMOD Test.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/abuba/Desktop/CMOD Test/CMOD Test.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
